"""
AI Output Data Models.

Internal Pydantic models that represent the structured workout plan
generated by the AI. Used for validation of the LLM's JSON output
before it reaches the API layer.
"""

from pydantic import BaseModel, Field


class WarmUpExercise(BaseModel):
    exercise: str
    duration: str


class Exercise(BaseModel):
    name: str
    sets: int = Field(..., ge=1, le=10)
    reps: str  # Can be "10-12" or "30 seconds"
    rest_between_sets: str
    form_tip: str


class WorkoutDay(BaseModel):
    day: str
    focus: str
    is_rest_day: bool = False
    warm_up: list[WarmUpExercise] = []
    exercises: list[Exercise] = []
    cool_down: list[WarmUpExercise] = []


class WorkoutPlan(BaseModel):
    """Complete AI-generated workout plan."""
    plan_name: str
    summary: str
    weekly_schedule: list[WorkoutDay] = Field(..., min_length=7, max_length=7)
    notes: str = ""
